service: resort-server

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  resortFunction: 
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'