name: Deploy

on:
  push:
    branches:
    - main
    
jobs: 
  service: 
    name: serverless
  custom:
    webpack:
      webpackConfig: ./webpack.config.js
      includeModules: true
  plugins:
    - serverless-webpack
    - serverless-offline
  provider:
    name: aws
    runtime: nodejs12.x
    apiGateway:
      minimumCompressionSize: 1024
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  functions:
    resort:
      handler: src/index.handler
      events:
        - http: 'ANY {proxy+}'

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: Setting up serverless config credentials from AWS
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy
        run: serverless deploy